### ISSUE TITLE
No reference to using zodern:melte package

### ISSUE THREAD

**Issue by shankscoder** [meteor/svelte-tutorial#1]
The [Collections Section](https://svelte-tutorial.meteor.com/simple-todos/02-collections.html) and other parts of the tutorial make reference to using the `$m` extension, which is exposed by using the `zodern:melte` package. 

The default `meteor --create svelte` skeleton doesn't use this package, and instead uses `rdb:svelte-meteor-data` which doesn't have this extension.

If the tutorial is going to use the `$m` extension, the `Creating an app` section needs to provide instructions on how to swap out `rdb:svelte-meteor-data` for `zodern:melte` package.

**Comment by denihs** [comment]
Hi @shankscoder, 

Thanks for this and yes, this is really a problem. We'll fix this on this [PR](https://github.com/meteor/meteor/pull/11389/files) that stops using `svelte:compiler ` and starts using `zodern:melte`. It'll be available in the next Meteor Version.

I'll close this for now. If you have questions, let me know.
